export const dummyData = {
  SleepData: {
    time: "8 h",
    percentage: "+10",
    data: [
      { value: 150 },
      { value: 50 },
      { value: 200 },
      { value: 250 },
      { value: 350 },
    ],
  },
  ActivityData: {
    time: "12 h",
    percentage: "+30",
    data: [
      { value: 200 },
      { value: 300 },
      { value: 100 },
      { value: 200 },
      { value: 150 },
      { value: 250 },
      { value: 250 },
      { value: 350 },
    ],
  },
  EfficiencyData: {
    efficiency: "2 EX",
    percentage: "+70",
    data: [
      { value: 100 },
      { value: 200 },
      { value: 300 },
      { value: 250 },
      { value: 150 },
      { value: 250 },
      { value: 200 },
      { value: 350 },
    ],
  },
  FoodData: {
    pieData: [
      { name: "Protein", value: 100 },
      { name: "Fats", value: 42 },
      { name: "Carbs", value: 90 },
      { name: "Water", value: 80 },
    ],
    label: "60",
    COLORS: ["#8884d8", "#FF007A", "#9C27B0", "#B39DDB"],
  },
  personalData: {
    gender: "Man",
    age: "33 years old",
    height: "180 cm",
    weight: "90 kg",
    bloodPressure: "120/80",
    activityEnergy: "800 kcal",
    restEnergy: "1200 kcal",
    bust: "120 cm",
    waist: "80 cm",
  },
  AnalyticsData: [
    { name: "Je", Sleep: 40, Activity: 24 },
    { name: "Fe", Sleep: 30, Activity: 13 },
    { name: "Ma", Sleep: 20, Activity: 98 },
    { name: "Ap", Sleep: 27, Activity: 39 },
    { name: "May", Sleep: 18, Activity: 48 },
    { name: "June", Sleep: 23, Activity: 38 },
    { name: "Jul", Sleep: 34, Activity: 43 },
    { name: "Aug", Sleep: 40, Activity: 24 },
    { name: "Sep", Sleep: 30, Activity: 13 },
    { name: "Oct", Sleep: 20, Activity: 98 },
  ],
  stretchData: {
    trainingTime: "0:45:30",
    totalCalories: 150,
    exercises: 15,
    activePressure: "125/78",
    heartRate: "65 BPM",
    normalPressure: "120/80",
    restingRate: "60 BPM",
    completion: 60,
    stretchPercentagedata: [
      { name: "Completed", value: 60 },
      { name: "Remaining", value: 40 },
    ],
    histogramData: [
      { name: "0", value: 30 },
      { name: "1", value: 20 },
      { name: "2", value: 27 },
      { name: "3", value: 18 },
      { name: "4", value: 23 },
      { name: "5", value: 34 },
      { name: "6", value: 26 },
      { name: "7", value: 21 },
      { name: "8", value: 29 },
      { name: "9", value: 30 },
      { name: "10", value: 24 },
      { name: "11", value: 25 },
      { name: "12", value: 27 },
      { name: "13", value: 22 },
      { name: "14", value: 28 },
    ],
  },
  runningData: {
    trainingTime: "1:20:45",
    totalCalories: 350,
    distance: "6 km",
    activePressure: "140/85",
    heartRate: "75 BPM",
    normalPressure: "120/80",
    restingRate: "65 BPM",
    completion: 100,
    runningPercentagedata: [
      { name: "Completed", value: 100 },
      { name: "Remaining", value: 0 },
    ],
    zones: [
      {
        name: "Zone 1",
        time: "05:12",
        bpm: "< 138 BPM",
        color: "purple-500",
      },
      {
        name: "Zone 2",
        time: "05:30",
        bpm: "139-150 BPM",
        color: "blue-500",
      },
      {
        name: "Zone 3",
        time: "04:12",
        bpm: "151-138 BPM",
        color: "green-500",
      },
      {
        name: "Zone 4",
        time: "16:49",
        bpm: "163-138 BPM",
        color: "orange-500",
      },
      {
        name: "Zone 5",
        time: "20:02",
        bpm: "> 174 BPM",
        color: "red-500",
      },
    ],
    histogramData: [
      { name: "0", value: 30 },
      { name: "1", value: 20 },
      { name: "2", value: 27 },
      { name: "3", value: 18 },
      { name: "4", value: 23 },
      { name: "5", value: 34 },
      { name: "6", value: 26 },
      { name: "7", value: 21 },
      { name: "8", value: 29 },
      { name: "9", value: 30 },
      { name: "10", value: 24 },
      { name: "11", value: 25 },
      { name: "12", value: 27 },
      { name: "13", value: 22 },
      { name: "14", value: 28 },
    ],
  },
};
