export const combinedData = {
  data: [
    { value: 100 },
    { value: 200 },
    { value: 150 },
    { value: 250 },
    { value: 200 },
    { value: 300 },
    { value: 250 },
    { value: 350 },
  ],
  FoodData: {
    pieData: [
      { name: "Protein", value: 100 },
      { name: "Fats", value: 42 },
      { name: "Carbs", value: 90 },
      { name: "Water", value: 500 },
    ],
    label: "60%",
    COLORS: ["#8884d8", "#FF007A", "#9C27B0", "#B39DDB"],
  },
  personalData: {
    gender: "Man",
    age: "33 years old",
    height: "180 cm",
    weight: "90 kg",
    bloodPressure: "120/80",
    activityEnergy: "800 kcal",
    restEnergy: "1200 kcal",
    bust: "120 cm",
    waist: "80 cm",
  },
  AnalyticsData: [
    { name: "Je", Sleep: 40, Activity: 24 },
    { name: "Fe", Sleep: 30, Activity: 13 },
    { name: "Ma", Sleep: 20, Activity: 98 },
    { name: "Ap", Sleep: 27, Activity: 39 },
    { name: "May", Sleep: 18, Activity: 48 },
    { name: "June", Sleep: 23, Activity: 38 },
    { name: "Jul", Sleep: 34, Activity: 43 },
    { name: "Aug", Sleep: 40, Activity: 24 },
    { name: "Sep", Sleep: 30, Activity: 13 },
    { name: "Oct", Sleep: 20, Activity: 98 },
  ],
  stretchData: {
    trainingTime: "1:10:15",
    totalCalories: 250,
    exercises: 250,
    activePressure: "130/80",
    heartRate: "70 BPM",
    normalPressure: "120/80",
    restingRate: "60 BPM",
    completion: 40,
  },
  strechPercentagedata: [
    { name: "Completed", value: 40 },
    { name: "Remaining", value: 60 },
  ],
  runningData: {
    trainingTime: "1:10:15",
    totalCalories: 250,
    exercises: 250,
    activePressure: "130/80",
    heartRate: "70 BPM",
    normalPressure: "120/80",
    restingRate: "60 BPM",
    completion: 100,
  },
  runningPercentagedata: [
    { name: "Completed", value: 40 },
    { name: "Remaining", value: 60 },
  ],
};
